AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda with spring boot.

Resources:
  LambdaSpringBootFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.brainupgrade.aws.serverless.lambda.handler.AWSLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: target/brainupgrade-aws-springboot-lambda-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events: 
        GetResource: 
          Type: Api 
          Properties: 
            Path: /{proxy+}
            Method: Any
            
Outputs: 
  LambdaSpringBootApi: 
    Description: API URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/languages'
    Export: 
      Name: LambdaSpringBootApi