cloud: 
  aws:
    region:
      use-default-aws-region-chain: true
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials: 
      access-key: AKIASQFWPBQYFFIQ66UF
      secret-key: 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  
logging:  
  level:   
    com: 
      amazonaws:  
        util: 
          EC2MetadataUtils: error
        internal: 
          InstanceMetadataServiceResourceFetcher: error